inherit_from: ../.rubocop.yml

plugins:
  - rubocop-rspec

AllCops:
  # Exclude generated files
  Exclude:
    - 'suite/**/*'

Style/MultilineBlockChain:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

RSpec/ExampleLength:
  Exclude:
    - 'berkeley_library/marc/field_info/**/*.rb'
    - 'marc_extensions/*.rb'

RSpec/RepeatedExampleGroupDescription:
  Exclude:
    - 'berkeley_library/marc/field_info/**/*.rb'

RSpec/MultipleExpectations:
  Exclude:
    - 'berkeley_library/marc/field_info/**/*.rb'
    - 'marc_extensions/*.rb'

RSpec/SpecFilePathFormat:
  Exclude:
    - 'marc_extensions/*.rb'

############################################################
# Added in Rubocop 0.89

# Sometimes we're testing the operator
Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: false
